# Latest golang image on apline linux
FROM golang:1.23.1-alpine

# Work directory
WORKDIR /web

# Installing dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copying all the files
COPY . .

# Starting our application
CMD ["go", "run", "./cmd/web/main.go"]

# Exposing server port
EXPOSE 8080