ServiceHost = "0.0.0.0"
ServicePort = 8080

[minio]
user = "it_maniac"
pass = "minio_accomplice_18"
endpoint = "127.0.0.1:9000"

[redis]
DialTimeout = "10s"
ReadTimeout = "10s"
REDIS_HOST="0.0.0.0"
REDIS_PORT=6379
REDIS_USER="borizzler"
REDIS_PASSWORD="redis123"

[postgresql]
DB_HOST="0.0.0.0"
DB_PORT=5432
DB_NAME="weather_db"
DB_USER="root"
DB_PASS="pgpwd"

[JWT]
Key = "RecallAllYourMind"