basePath: /
definitions:
  handler.loginResp:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
  main.pingResp:
    properties:
      status:
        type: string
    type: object
host: 127.0.0.1
info:
  contact:
    email: borislarkin18@mail.ru
    name: API Support
    url: https://vk.com/b.larkin
  description: Bmstu Open IT Platform
  license:
    name: AS IS (NO WARRANTY)
  title: Forecast system
  version: "1.0"
paths:
  /ping/{name}:
    get:
      description: very very friendly response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.pingResp'
      summary: Show hello text
      tags:
      - Tests
  /user/login:
    post:
      description: very very friendly response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.loginResp'
      summary: Login the specified user
      tags:
      - Users
schemes:
- https
- http
swagger: "2.0"
